import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { ReactElement, useEffect, useState } from "react";
import Layout from "../components/layout";
import NoDragImage from "../components/noDragImage";
import { trpc } from "../utils/trpc";
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  const [url, setUrl] = useState("");
  const router = useRouter();
  const { data: images } = trpc.images.getAll.useQuery(undefined, {
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
  });

  useEffect(() => {
    setUrl(window.location.origin);
  }, []);

  if (url === "") {
    return <div>Loading</div>;
  }

  return (
    <>
      <Head>
        <title>Ziimgur - Easy file hosting solution</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full flex-col items-center gap-y-4">
        {images
          ? images.map((img, i) => {

              return (
                <div key={i}>
                    <NoDragImage
                      src={`${url}/api/${img.id}.${img.extension}`}
                      alt={``}
                      width={0}
                      sizes={"100vw"}
                      height={0}
                      style={{ width: "720px", height: "auto" }}
                    />
                </div>
              );
            })
          : null}
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
