import Layout from "@/components/layout";
import LayoutWrapper from "@/components/layout/layoutWrapper";
import Navbar from "@/components/layout/navbar";
import NoDragImage from "@/components/noDragImage";
import { trpc } from "@/utils/trpc";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { ReactElement, useEffect, useState } from "react";
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  const [url, setUrl] = useState("");

  const client = trpc.useContext();

  const { data: session } = useSession();

  const { data: images } = trpc.images.getAll.useQuery(
    { amount: 25 },
    {
      onSuccess: () => {
        client.user.getAll.invalidate({ id: session?.user?.id });
      },
      refetchOnWindowFocus: false,
    }
  );

  useEffect(() => {
    setUrl(window.location.origin);
  }, []);

  if (url === "") {
    return <div>Loading</div>;
  }

  return (
    <>
      <Head>
        <title>Ziimgur - Easy file hosting solution.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="columns-5 space-y-4">
        {images
          ? images.map((img, i) => {
              return (
                <NoDragImage
                  key={i}
                  src={`${url}/api/${img.id}.${img.extension}`}
                  alt={``}
                  width={0}
                  sizes={"100vw"}
                  height={0}
                  className={"h-fit w-[300px] break-inside-avoid"}
                />
              );
            })
          : null}
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      <Navbar />
      <LayoutWrapper>{page}</LayoutWrapper>
    </Layout>
  );
};

export default Home;
