import Head from "next/head";
import { ReactElement, useEffect, useState } from "react";
import { parse, stringify } from "superjson";
import { z } from "zod";
import Layout from "../components/layout";
import { trpc } from "../utils/trpc";
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  const [image, setImage] = useState<File | null>(null);
  const [text, setText] = useState<Uint8Array | null>(null);
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  useEffect(() => {
    const getData = async () => {
      if (image) {
        const foundText = await image.arrayBuffer();
        const uint = new Uint8Array(foundText);
        setText(uint);

        console.log("BlogString", uint);
      } else {
        setText(null);
      }
    };

    getData()
      .then((e) => {
        console.log("E", e);
      })
      .catch((err) => {
        console.error("Err", err);
      });
  }, [image]);

  const { mutate: UploadImage } = trpc.images.create.useMutation();
  const { mutate: UploadFromURL } = trpc.images.create2.useMutation();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full flex-col">
        <input
          className="my-2 w-fit rounded bg-transparent p-1 outline outline-zimgur-900"
          type={"file"}
          onChange={(e) => {
            if (e.target.files && e.target.files[0]) {
              const url = new URL("https://i.imgur.com/b4FUSGg.png");
              UploadFromURL({
                url: url.toString(),
              });
              setImage(e.target.files[0]);
            }
          }}
        ></input>
        <button
          className="my-2 w-fit rounded bg-transparent p-1 outline outline-zimgur-900"
          type={"submit"}
          formMethod={"post"}
          formEncType="multipart/form-data"
          onClick={(e) => {
            if (image && text) {
              // const test: FormData = image;
              // console.log(test);
              UploadImage({
                image: text,
                type: image.type,
                extension: image.name.substring(
                  image.name.lastIndexOf(".") + 1
                ),
              });
            }
          }}
        >
          Upload
        </button>
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
